### ISSUE TITLE
Error when running on a system on which Blender did not run before

### ISSUE THREAD

**Issue by probonopd** [MutableLoss/blender-config-manager#1]
Unhandled error when running on a system on which Blender did not run before:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/40a45ce20ab1c9ba6a25325dde3714ea9da5f748/database/Blender_Config_Manager/screenshot.png)

A default configuration should be copied into `$HOME` in this case.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1124

**Comment by 3DEsprit** [comment]
Thanks for that @probonopd ! I'll be sure to update that with the new version coming up.

**Comment by probonopd** [comment]
Please let me know once the new version is out so that we can include the app in https://appimage.github.io/.

**Comment by 3DEsprit** [comment]
I certainly will, and I should have the new builds in the next week. I'll be sure to mention you here once it's updated. 👍

Thanks!

**Comment by 3DEsprit** [comment]
Fixed in Release 1.1.0

https://github.com/3DEsprit/blender-config-manager/releases/1.1.0

**Comment by 3DEsprit** [comment]
@probonopd there is another project of mine using AppImage, but it's on the Blender Market. I wasn't sure if you ever added anything like that, but I wanted to at least let you know:

https://blendermarket.com/products/barista

If you're interested, I can get an icon to you, and anything else you need since there isn't a public repository.

I'll also try to fix the image for the Blender Config Manager, that way it doesn't default to the Electron placeholder.

**Comment by probonopd** [comment]
Thanks @MutableLoss. In order for anything to be added to the AppImage/appimage.github.io catalog it needs to run through the fully automated test. If you can mail me a temporary download link (you can remove it right after the test has run) then I could run the test and if it passes your app would automatically be added to the catalog.

**Comment by MutableLoss** [comment]
Thanks for the reply @probonopd ! What is the email you want that sent to, or is there another place you prefer I follow up? No matter what I will be happy to send you a download link, or if by chance you have a Blender Market account, we can link a copy to your account. 👍
